from genrl.classical.bandit.data_bandits.covertype_bandit import CovertypeDataBandit
from genrl.classical.bandit.data_bandits.data_bandit import DataBasedBandit
from genrl.classical.bandit.data_bandits.mushroom_bandit import MushroomDataBandit
from genrl.classical.bandit.data_bandits.statlog_bandit import StatlogDataBandit
